### ISSUE TITLE
fusion-framework-cli ignoring -c flag

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/fusion-framework#1434]
**Describe the bug**
Trying to use `fusion-framework-cli app dev -c ./app.config.local.js` the -c flag seems to be ignored.

**Environment**

Windows
fusion-framework-cli@9.2.1
node@18.15.0

**To Reproduce**
 run the following command `fusion-framework-cli app dev -c ./app.config.local.js` check the config request in network tab of devtools. See if contents corresponds to file contents

**Expected behavior**
Expected fusion framework to use app.config.local.js instead of app.config.js or remote app config.

**Stacktrace**
If applicable, add stacktrace to help explain your problem.

**Additional context**

**Comment by odinr** [comment]
🍻 will look into it
