### ISSUE TITLE
Context Id not being set or cleared in url

### ISSUE THREAD

**Issue by Jonathanio123** [equinor/fusion-framework#1477]
**Describe the bug**
In the old Fusion Cli the contextId was synced with the url. So when a context was selected it was set in url: baseurl/contexid. Subsquently it was cleared when you cleared the context trough the context selector. 

**Environment**

- OS Windows 11
- Node Version

**To Reproduce**
New Framework cli:
`Removed due to sensitive material`

Old Fusion Cli:
`Removed due to sensitive material`

**Expected behavior**
Same behavior as the old cli?

**Additional context**

**Comment by odinr** [comment]
@Jonathanio123 could you leave a link to the repo, so that i can test the code?

**Comment by Jonathanio123** [comment]
@odinr https://github.com/equinor/fusion-app-maturity-matrix-frontend
On this branch [feat/fusion-framework-cli](https://github.com/equinor/fusion-app-maturity-matrix-frontend/tree/feat/fusion-framework-cli)

**Comment by odinr** [comment]
ok, sorry for the long wait, but i figured out that the CLI does not have a build in `change url on context`, since some portals have different URL schema, i will discuss how/if we implement it for the dev CLI.
hang in tight, we will update this issue

**Comment by odinr** [comment]
closed by #1933
