### ISSUE TITLE
Typed props missing in createFrameworkProvider

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-framework#179]
When creating a `framework` provider the type seems wrong, and gives the following error.
Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'.ts(2559)

I purpose this change to fix the issue. for now ill cast it my self but should be fixed

```TS
export const createFrameworkProvider = <TModules extends Array<AnyModule> = []>(
    configurator: FusionConfigurator<TModules>,
    modules?: TModules
): React.LazyExoticComponent<React.FunctionComponent<{ children?: React.ReactNode }>> =>
    lazy(async () => {
        const framework = await initFusion(configurator, modules);
        return {
            default: ({ children }: { children?: React.ReactNode }) => (
                <FrameworkProvider value={framework}>{children}</FrameworkProvider>
            ),
        };
    });

```

**Comment by odinr** [comment]
hmmm, which version of node are you using and OS?
I do not get any errors when using this in the[ test app](https://github.com/equinor/fusion-framework/blob/e96b8c61fbb8d13fc1ff66f8062419ca61ff024d/packages/test-app/src/index.tsx#L13)

could you link to the code that your using which gives the error

**Comment by odinr** [comment]
cant reproduce, closed missing response
issue outdated
