### ISSUE TITLE
Wrap fusion instance in proxy

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/fusion-framework#302]
**Is your feature request related to a problem? Please describe.**
To prevent any consumers from altering the fusion instance, wrapping it in a proxy could be a feasible solution.

**Describe the solution you'd like**
```TS
/**
 *  Wraps an object and all its children objects in a proxy 
 *  Handles arrays and objects
 */
function deepProxy<T extends Record<PropertyKey,any>>(obj: T){
    Object.keys(obj).filter(key => typeof obj[key] === "object").filter(key => obj[key] !== null).forEach(key => {
        obj[key as keyof T] = deepProxy(obj[key])
    })
    return new Proxy(obj, {set(){return false}})
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by odinr** [comment]
yes that could work 🤙🏻
but there might be sub object which the user want to set properties... maybe.
