### ISSUE TITLE
Global style hides SVGs

### ISSUE THREAD

**Issue by siglar** [equinor/fusion-framework#373]
**Describe the bug**
A global style tag hides certain SVGs.

**Environment**
In production (fusion.equinor.com).
It does not happen when one builds locally.

**To Reproduce**
Deploy app...

**Expected behavior**
SVG should render.

**Additional context**
GIF of whats happening. Seem like there is a SVG style tag that is set globally that screws things up.

![svg_gone](https://user-images.githubusercontent.com/3383006/199490984-5a472cc7-115f-48cd-8755-2d6b53e19365.gif)

**Comment by eikeland** [comment]
Issue is being fixed in a portal pr.

**Comment by siglar** [comment]
This no longer is a problem (in our app at least). You can close the issue if you think it's solved.
