### ISSUE TITLE
Path parsing windows fusion cli

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/fusion-framework#754]
**Describe the bug**
When running `fusion-framework-cli app dev` the main entry must be in this format  `"main": "/src/main.tsx"`, but when running 
`fusion-framework-cli app build` the main entry must be like this `"main": "./src/main.tsx"`.

Im assuming this is working correctly on Linux/MacOS. But on Windows it is not working. A simple fix could be accepting a entrypoint as cli argument, with a fallback to package.json.

**Environment**

- OS - Windows
- Node Version - v18.15.0

**Comment by odinr** [comment]
this was fixed in #1194
