### ISSUE TITLE
[CLI] - Set margin to 0px in dev portal

### ISSUE THREAD

**Issue by jaysencpp** [equinor/fusion-framework#828]
![image](https://user-images.githubusercontent.com/28650210/235617028-75dca561-c07e-4f87-8014-35338f70e5a1.png)

Messes with the total height and scrollbars..

**Comment by jaysencpp** [comment]
Unrelated to margin, it seems like the main container containing the  Header and Outlet component does not get the correct height. The Header component pushes the outlet down, causing a scollbar. Could probably fix with giving the container node some more styling..

**Comment by odinr** [comment]
fixed in #1194
