### ISSUE TITLE
Fusion-framework-cli: PersonResolver need's a method for querying against person name.

### ISSUE THREAD

**Issue by eikeland** [equinor/fusion-framework#964]
**Is your feature request related to a problem? Please describe.**
The current PersonResolver in the ffw-cli only has methods to retrieve person details based on azureid, a method for general query for persons is missing.

**Describe the solution you'd like**
A new method for person query against name and email in the PersonResolver.

**Describe alternatives you've considered**
Adding an PersonResolver in the app when needed..

**Comment by odinr** [comment]
closed by #1257 and #1255
