### ISSUE TITLE
Vite build options not available

### ISSUE THREAD

**Issue by adukstad** [equinor/fusion-framework#997]
**Describe the bug**
Build options passed to the cli is not passed on to the underlying `vite build`.
Options are found [here](https://vitejs.dev/guide/cli.html)

Ideally we would like to all options to be available, but the most important ones is :
` --config`,  alternatively `--sourcemap`

**Environment**

- OS: All
- Node Version: 18

**To Reproduce**

`  "scripts": {
    "build": "fusion-framework-cli app build",
  },` &&  `npm run build -- --config vite.config.prod.js`
**Expected behavior**
Ability to choose which config file to use as per [vite docs](https://vitejs.dev/guide/cli.html)
**Stacktrace**
`error: unknown option '--config'`

**Comment by odinr** [comment]
seems like a fair request, will add to backlog
